### ISSUE TITLE
Directory errors with Docker installation

### ISSUE THREAD

**Issue by besnardf** [Nakiami/mellivora#108]
Hi,

Running the installation using Docker and the available `docker-compose.dev.yml` file, it seems that some permissions are lacking for the CTF platform to run properly.

Indeed, for instance, an administrator is not able to upload challenges to the platform.

You may want to take a look at the attached pictures.

A remediation would be to modify the Dockerfile and setting the right permissions on the folders.

<img width="249" alt="permissions" src="https://user-images.githubusercontent.com/22943342/42624201-1a9c9e0c-85c5-11e8-8e2f-317df41f4218.PNG">
<img width="629" alt="error" src="https://user-images.githubusercontent.com/22943342/42624200-1a5e21c2-85c5-11e8-880c-e22f1a74fe9f.PNG">

**Comment by Nakiami** [comment]
Thanks, clarified in https://github.com/Nakiami/mellivora/commit/75c9d4bf6bb91f7c8c1fe4df525f2c48a6e6746d.
