### ISSUE TITLE
admin configuration page 

### ISSUE THREAD

**Issue by Numtelmuun** [Nakiami/mellivora#118]
Hello, 

Can i configure CTF and user management from Web?

**Comment by Numtelmuun** [comment]
SiteURL+ADMIN_RELPATH doesn't work so I can't access admin URL.

**Comment by MoonfireSeco** [comment]
I'm not sure whether there's an official way to do this, but I created an admin user for myself through the sql shell, then logged in with it.

**Comment by Numtelmuun** [comment]
> I'm not sure whether there's an official way to do this, but I created an admin user for myself through the sql shell, then logged in with it.

please can u help me create an admin user. I tried to this a lot time.

**Comment by Nakiami** [comment]
The install instructions all have information about how to set up an admin: https://github.com/Nakiami/mellivora/blob/master/install/README.md
