### ISSUE TITLE
Documentation on installing on Ubuntu should be updated

### ISSUE THREAD

**Issue by klausagnoletti** [Nakiami/mellivora#125]
Hi

Instructions when installing on ubuntu doesn't include instructions that on never version, authentification via password by root user is disabled. More info (and instructions on changing that) on https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-18-04

Thanks

/klaus

**Comment by Nakiami** [comment]
Hi, correct, the instructions are for Ubuntu 16.04. Feel free to submit a PR with updated instructions for 18 if you've recently done the setup. Thanks

**Comment by Nakiami** [comment]
Updated to target Ubuntu 20.04
