### ISSUE TITLE
Disable registration mail sending.  Suggestion for solution

### ISSUE THREAD

**Issue by janfer** [Nakiami/mellivora#136]
I wanted to disable mail sending totally since we do not have access to Internet where we run CTF.   This is my suggestion for a solution.  

--- config.ing.php -----
**Config::set('MELLIVORA_CONFIG_EMAIL_NO_MAIL', true);**

---- email.inc.php -----
 // MOD to skip sending registrations mail first statement in function send_mail()
    **if (Config::get('MELLIVORA_CONFIG_EMAIL_NO_MAIL')){
            return $receivers;
    }**

**Comment by Nakiami** [comment]
Hi, feel free to create a pull request
