### ISSUE TITLE
How to open admin panel

### ISSUE THREAD

**Issue by PunitTailor55** [Nakiami/mellivora#139]
Hi I have installed mellivora in aws ec2 instance successfully. I am not able to open admin panel. Can anybody help me out? I have added `MELLIVORA_CONFIG_SITE_ADMIN_URL` in `config.inc.php` but it is still redirecting to `site/home`.

**Comment by nunoguerreiro** [comment]
same

**Comment by Nakiami** [comment]
Hi, you don't need to chang `MELLIVORA_CONFIG_SITE_ADMIN_URL` to access the admin panel. Did you create an admin user? Did you follow the instructions? https://github.com/Nakiami/mellivora/tree/master/install

**Comment by PunitTailor55** [comment]
I have followed given steps to install admin panel. Created admin user as well but still getting error.

**Comment by Nakiami** [comment]
What error?
