### ISSUE TITLE
Exceptions containing credentials

### ISSUE THREAD

**Issue by DISC2014** [Nakiami/mellivora#38]
Site exceptions store and record user credentials. Moderators can then see the list...Any possibility of a 'Clear Exceptions' functionality?

**Comment by Nakiami** [comment]
Thanks. Could the edit page go on a separate edit_exceptions page? That could be linked to at the top of list_exceptions (similar to what's done in profile.php), as well as in the menu. That way the delete form isn't included on every page of the exceptions list.
