### ISSUE TITLE
Multiple correct submissions get extra points

### ISSUE THREAD

**Issue by janderse** [Nakiami/mellivora#43]
If there are multiple correct submissions for the same challenge for the same user, the user will get extra points for them.  For example, if they have 3 answers marked correct for the same 50 point question, they will get 150 points instead of the 50 points they should get.

Repro:
Answer a challenge incorrectly twice.  Manually mark both submissions correct.  View the scores, and the individual score page.  The user got double points for the challenge.

**Comment by Nakiami** [comment]
Good find. Please see comment on: https://github.com/Nakiami/mellivora/issues/41#issuecomment-93149326

**Comment by Nakiami** [comment]
Fixed in https://github.com/Nakiami/mellivora/commit/5d3932086e4643eb272c04352d79647e447a66bf
