### ISSUE TITLE
Disabled user can still make submissions

### ISSUE THREAD

**Issue by janderse** [Nakiami/mellivora#44]
A disabled user can still make submissions.  They cannot login, but they can still see the challenges and get points.

Repro:
 * User: Register a new user.
 * User: Login.
 * Administrator: Login in another browser
 * Administrator: Uncheck the "enabled" checkbox for the user and save.
 * User: Submit an answer.  View challenges.  Etc.

Expected: User cannot make submissions since their account is not enabled.
Actual: User can make submissions.

**Comment by Nakiami** [comment]
Nice! Disabled users should definitely be logged out when they're disabled. I'd suggest the following though: modify session.inc.php:enforce_authentication and session.inc.php:login_session_refresh to optionally reload and check the user credentials from the db. If the user is no longer enabled, call logout().

**Comment by Nakiami** [comment]
Fixed in https://github.com/Nakiami/mellivora/commit/313ef1dfa798996ea9a22c75a019045269e56168
