### ISSUE TITLE
Password Change Always Fails When 2FA is Enabled

### ISSUE THREAD

**Issue by ussjoin** [Nakiami/mellivora#48]
Steps to reproduce:

1. Create an account.
2. Enable 2FA.
3. Attempt to change password.
4. Enter OTP when prompted.

Expected result:

"Success" notification.

Actual result:

No notification. Upon logging out, old password works, new password does not.

This is made more problematic by not being able to disable 2FA from the user interface, and therefore having to disable 2FA via MySQL commands, *then* change the pw, *then* re-enable 2FA.

**Comment by Nakiami** [comment]
Thanks! Fixed in https://github.com/Nakiami/mellivora/commit/40ec1c3b400d884d7af2ef2df09104bd0fd9f9c5
