### ISSUE TITLE
Unsigned varchar causing import error :: mellivora.sql

### ISSUE THREAD

**Issue by Shad0wSt3p** [Nakiami/mellivora#57]
mellivora.sql

Line 84:  `code` varchar(10) unsigned NOT NULL,

varchar should not be unsigned? Errors out in MySQL on import.

**Comment by Nakiami** [comment]
Thanks. Fixed in https://github.com/Nakiami/mellivora/commit/a60117f3d3bae303355b0057f7d0420f92a03eb4
