### ISSUE TITLE
SSL support removed from mellivora.conf

### ISSUE THREAD

**Issue by Shad0wSt3p** [Nakiami/mellivora#60]
I noticed in a recent cleanup the SSL options were removed; is this functionality implemented elsewhere or for the user to input manually?

**Comment by Nakiami** [comment]
Hi! I assume you mean this commit? https://github.com/Nakiami/mellivora/commit/74ec33f3c4cc1c9a08de67db37ce02dc6869b22c#diff-f24af0ecd0b9e5beadd10cde17c3f4e5R46

This only means that by default the mellivora site will not force SSL on the login and register pages. If you're running your site with ssl, like https://ctf.yoursite.com/, then you can set ``CONFIG_SSL_COMPAT`` to true. If you're doing local dev, or running the site without ssl, leave it as false.
