### ISSUE TITLE
Challenges not showing

### ISSUE THREAD

**Issue by semprix** [Nakiami/mellivora#63]
Only 1 challenge is being showed on /challenges and submission button is not visible.

**Challenge management**
![image](https://cloud.githubusercontent.com/assets/208085/14876282/e2f3f36e-0d45-11e6-89ca-616a46a2b20d.png)

**Challenge page**
Only 1 challenge showed on this category, "Submission button is also missing"
![image](https://cloud.githubusercontent.com/assets/208085/14876293/f9ab9e86-0d45-11e6-8c06-7cbf583b4940.png)

Not sure if this is a bug or it has something to do with some settings.

**Comment by Shad0wSt3p** [comment]
Have you set the time for release yet? Maybe it's set to open in the future. Additionally, ensure your server has NTP set up and is synced properly with your timezone :)

**Comment by Nakiami** [comment]
If I had to guess I'd say, as Shad0wSt3p pointed out, that you probably have some differences in time[zone] configuration between one or all of your web server, php, database and os..

**Comment by Nakiami** [comment]
I just added a timezone check for the admin page. Try pulling the latest version and see if it triggers. There should be a red box with warnings on the admin page if the timezones are different.

**Comment by semprix** [comment]
Timezone setting on OS and php.ini are both set correctly, how about the submission button missing?

**Comment by semprix** [comment]
Issue is exist after pulling the latest commits...

**OS Version:**
Debian 8.4
root@ctfbox:/var/www/mellivora/include# uname -a
Linux ctfbox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**PHP Version:** 
root@ctfbox:/var/www/mellivora/include# php --version
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
root@ctfbox:/var/www/mellivora/include# 

**Debian Timezone**
root@ctfbox:/var/www/mellivora/include# cat /etc/timezone 
**Asia/Manila**
root@ctfbox:/var/www/mellivora/include# 

**PHP Timezone**
root@ctfbox:/var/www/mellivora/include# cat /etc/php5/apache2/php.ini | grep date.timezone
; http://php.net/date.timezone
**date.timezone = "Asia/Manila"** 
root@ctfbox:/var/www/mellivora/include# 

**MySQL Timezone**
mysql> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
1 row in set (0.00 sec)

**Screenshots**
![image](https://cloud.githubusercontent.com/assets/208085/14906662/82cd2874-0df0-11e6-8464-aab02f2cada7.png)

![image](https://cloud.githubusercontent.com/assets/208085/14906668/90cd4116-0df0-11e6-8eb9-f2f77e2552ef.png)

![image](https://cloud.githubusercontent.com/assets/208085/14906670/99929044-0df0-11e6-96ce-7952eb47993e.png)

**Comment by Nakiami** [comment]
Not sure what it could be. Could you upload or send me a database dump?

**Comment by semprix** [comment]
Hi you may download it from http://www.devio.us/~semprix/mellivora.zip included the htdocs and .sql file.

**Comment by Nakiami** [comment]
I imported the dump and it works fine on my end. Can you attach your configuration file?

**Comment by semprix** [comment]
Configs can be downloaded at http://www.devio.us/~semprix/configs.zip 

thanks

**Comment by Nakiami** [comment]
Can't see anything amiss there. Could you try manually forcing the timezone in your config file by uncommenting/updating two lines up the top?

`//const CONFIG_DATE_DEFAULT_TIMEZONE = 'Australia/Sydney';
//date_default_timezone_set(CONFIG_DATE_DEFAULT_TIMEZONE);`

Do you have any output in the apache log files?

**Comment by semprix** [comment]
This is the "Fatal" error, could this be the culprit?

![image](https://cloud.githubusercontent.com/assets/208085/14932834/3ef9e3d8-0eb0-11e6-8f34-dea278dc11bd.png)

Uncommented the timezone setting.

![image](https://cloud.githubusercontent.com/assets/208085/14932841/4fa25d78-0eb0-11e6-87fa-7617920f0dea.png)

Still nothing

![image](https://cloud.githubusercontent.com/assets/208085/14932845/5d1d23ca-0eb0-11e6-8263-5b461670ea2f.png)

Also I noticed that on /challenges URL the footer are gone....

**Comment by semprix** [comment]
This could be missing in composer?

**Comment by Nakiami** [comment]
Ah, yeah, you'll need php-pear installed. Try `apt-get install php-pear`

**Comment by semprix** [comment]
That works! closing this issue now.....

**Comment by iderbukh** [comment]
how to admin login username & password 
pls help
