### ISSUE TITLE
SQL exception multiple ungraded answers

### ISSUE THREAD

**Issue by ebdavison** [Nakiami/mellivora#66]
In reference to issue #41, I get the same SQL exception if I have multiple ungraded answers as well.  I have added the limit 1 to both subqueries (for ungraded as well as correct) and the error goes away.  This seems like a bandaid though rather than a real solution.

Our business goal is to actually allow, somehow, multiple correct answers.  For instance, "List all of the URLs where you found the correct answer to the challenge."  For that sort of answer, there needs to be more than one correct answer, especially with social engineering research, and allowing multiple answers for partial credit (maybe 10 points for the question if you get all 10 URLs and 1 point for each valid answer) would be great.

**Comment by Nakiami** [comment]
Should be somewhat mitigated in https://github.com/Nakiami/mellivora/commit/6ed7762f8b717e8bc69f7608127330b2923632a8

If you're still looking to support multiple correct answers for a challenge, feel free to open another enhancement request.
