### ISSUE TITLE
ubuntu 14.04 to 16.04

### ISSUE THREAD

**Issue by larrymcd** [Nakiami/mellivora#70]
I recently did an "do-release-upgrade" on a Ubuntu 14.04 box with working mellivora installed and running. After the upgrade complete it was not working. I had issues then with php and MySQL not working when tyring to go to the website I had setup. After the update I had to reinstall php which installed php7.0 vs php5 , and then enable php7.0 in apache2 with a2enmod php7.0. After that the I was still having an error with mbstring and apache, which then I installed php7.0-mbstring things starting to work at least for showing the pages, but I got an MySQL error on the main page saying it cant connect to the Database. I then installed php-mysql and it started to work again.

I started to do some testing and now I am getting errors when I try to add a new challenge
[Mon Aug 22 10:34:04.146537 2016] [:error] [pid 4889] [client 192.168.153.131:47370] PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'points' at row 1 in /var/www/mellivora/include/db.inc.php:41\nStack trace:\n#0 /var/www/mellivora/include/db.inc.php(41): PDOStatement->execute(Array)\n#1 /var/www/mellivora/htdocs/admin/actions/new_challenge.php(34): db_insert('challenges', Array)\n#2 {main}, referer: http://192.168.153.131/admin/new_challenge.php?category=8

It looks like some validation checking happening and it is failing if you don't fill in everything in the form. If you enter items into all the text boxes it seems to work fine. I checked the database and it does have the default values listed, but it seems like there is some validation checking going on.

To fix the issue I edited the php code in the new_challenge.php to match the "defaults" expected in the DB. After doing that it works ok.

I would like to suggest that you add a default value page for category and challenges on the manage page. This way you could also set some of the values like available from and until for questions. It also would fill in the page with defaults when you load it too.

Thanks for all the work on mellivora also.

l

**Comment by Nakiami** [comment]
Thanks! Fixed in https://github.com/Nakiami/mellivora/commit/2e463f26d412b26e78d761c34c4921cde1aad523 and https://github.com/Nakiami/mellivora/commit/9f5d7ff23bf78f3f6d1df58314d4d8a8de72af13.
