### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by m1guelpiedrafita** [Nakiami/mellivora#73]
**Warning**: Division by zero in _/include/layout/user.inc.php_ on line 32
The warning appears when you log in and go to public profile page.
Installation data:
0 challenges
2 categories
1 user (admin)

**Comment by Nakiami** [comment]
Thanks! Fixed in https://github.com/Nakiami/mellivora/commit/34ca6f274024499d71adb13ec968408e14c081de.
