### ISSUE TITLE
XSS / Duplicate $base_url in layout.inc.php

### ISSUE THREAD

**Issue by nbrisset** [Nakiami/mellivora#74]
Hello,

I found two issues in the pager( ) function of the [layout.inc.php](https://github.com/Nakiami/mellivora/blob/master/include/layout/layout.inc.php) file. I wanted to fix them myself ("DIY!"), and make my first pull request on Github, but each time, I encountered problems when modifying and replacing the file.

* A XSS vulnerability on the "Search" module, because $base_url is not filtered, i.e. with [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php).

![mellivora_xss](https://cloud.githubusercontent.com/assets/4249716/18808408/e66990bc-8261-11e6-9814-ac727fd88125.png)

* Each time the Next or Prev buttons are clicked, $base_url is duplicated (2x then 4x 8x etc.)

![mellivora_urlbase1](https://cloud.githubusercontent.com/assets/4249716/18808506/c6e91156-8264-11e6-8a0c-eee4d1f5c823.png)

... which, when we keep clicking on the Next button, leads to a very very long URI.

![mellivora_urlbase2](https://cloud.githubusercontent.com/assets/4249716/18808509/cbf9a2f0-8264-11e6-8ffe-174b290c0d8f.png)

**Comment by Nakiami** [comment]
That's very serious, thank you. Fixed in https://github.com/Nakiami/mellivora/commit/ee60d7ed3220be8cfadea496feacc9db0daa6725
