### ISSUE TITLE
Logic bug in allowed_email()

### ISSUE THREAD

**Issue by lanjelot** [Nakiami/mellivora#80]
Hey,

There is a logic bug in [`allowed_email()`](https://github.com/Nakiami/mellivora/blob/2d491c3/include/email.inc.php#L103) that prevents email rules from actually being enforced.

If email does not match any rule then email will be [allowed](https://github.com/Nakiami/mellivora/blob/2d491c3/include/email.inc.php#L119) because `$allowedEmail` is [initialized](https://github.com/Nakiami/mellivora/blob/2d491c3/include/email.inc.php#L104) to `true`.

**Comment by Nakiami** [comment]
Hi, this is intended behavior. Default action is to allow email. If you want default action to be deny, you can add a rule for that in the console.
