### ISSUE TITLE
Broken HTTPS w/ Lets EncryptCert

### ISSUE THREAD

**Issue by jaredestroud** [Nakiami/mellivora#96]
After enabling SSL within the app via ```Mellivora/include/config/config.inc.php```, the page appears broken in the browser. 
<img width="1275" alt="screen shot 2017-08-12 at 7 04 10 pm" src="https://user-images.githubusercontent.com/1250113/29244824-5b0b6044-7f91-11e7-8e47-fe492e57ed06.png">

Any ideas on how to resolve this?

Thanks!

**Comment by CarlosLannister** [comment]
You need to modify config.inc.php. Add https to CONFIG_SITE_URL and CONFIG_SITE_URL_STATIC_RESOURCES.

Just use `vim` `/var/www/mellivora/include/config/config.inc.php` and edit.
