### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mike-bailey** [Nakiami/mellivora#97]
This seems like a good candidate for a Dockerfile. Would that be something people would be interested in it? I could PR it.

**Comment by mike-bailey** [comment]
(presumably label as enhancement)

**Comment by Nakiami** [comment]
Added Docker/docker-compose support here: https://github.com/Nakiami/mellivora/commit/cd508007d2278bc8d1818e9d1d2a1671f61a69ce . Can probably be improved so feel free to add feedback. See also: https://github.com/Nakiami/mellivora/blob/master/install/docker/README.md

**Comment by nix-xin** [comment]
Nice! Thanks for making it happen. I'll jump in an check it out too.
