### ISSUE TITLE
Failure: The Travis CI build failed

### ISSUE THREAD

**Issue by emaragkos** [Nakiami/mellivora#99]
I have added one file and committed the pull request. 
This branch has no conflicts with the base branch but I am getting:
Failure: The Travis CI build failed

**Comment by Nakiami** [comment]
Thanks, the builds are for unrelated reasons.

**Comment by Nakiami** [comment]
Fixed in https://github.com/Nakiami/mellivora/commit/375df58691c6e8a8af27e1d7f090236c7be2cb5d
